name: Run Headed Browser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install and upgrade dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install --upgrade drissionpage  # 确保更新到最新版本
          pip install loguru

      - name: Run script with virtual display
        run: |
          xvfb-run -a python qwe.py
