name: Run Headed Browser

on:
  # This section defines the triggers for the workflow
  workflow_dispatch:  # This will add a "Run workflow" button in the GitHub UI
  schedule:
    - cron: '0 3 * * *' # You can also keep your existing scheduled trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install drissionpage loguru

      - name: Run script with virtual display
        run: |
          xvfb-run -a python qwe.py
